services:
  - type: web
    name: grading-api
    runtime: docker
    branch: master
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: gondola.proxy.rlwy.net
      - key: DB_PORT
        value: "13069"
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: IzQcyKndQhEtgRqcWQdGHPmgyDqPamZH